from PyQt4 import QtGui, QtCore 

def get_step_groupbox():
    step_groupbox = QtGui.QGroupBox()
    step_groupbox.setGeometry(QtCore.QRect(0, 10, 301, 151))
    step_groupbox.setTitle("")
    step_groupbox.setObjectName("step_groupbox")
    val_interval_field = QtGui.QLineEdit(step_groupbox)
    val_interval_field.setGeometry(QtCore.QRect(120, 50, 151, 25))
    val_interval_field.setObjectName("val_interval_field")
    value_interval = QtGui.QLabel(step_groupbox)
    value_interval.setGeometry(QtCore.QRect(10, 50, 91, 16))
    value_interval.setObjectName("value_interval")
    value_init = QtGui.QLabel(step_groupbox)
    value_init.setGeometry(QtCore.QRect(10, 20, 71, 16))
    value_init.setObjectName("value_init")
    val_inicio_field = QtGui.QLineEdit(step_groupbox)
    val_inicio_field.setGeometry(QtCore.QRect(120, 20, 151, 25))
    val_inicio_field.setObjectName("val_inicio_field")
    step_number = QtGui.QLabel(step_groupbox)
    step_number.setGeometry(QtCore.QRect(10, 70, 81, 31))
    step_number.setWordWrap(True)
    step_number.setObjectName("step_number")
    step_number_field = QtGui.QLineEdit(step_groupbox)
    step_number_field.setGeometry(QtCore.QRect(120, 80, 151, 25))
    step_number_field.setObjectName("step_number_field")
    compliance_label = QtGui.QLabel(step_groupbox)
    compliance_label.setGeometry(QtCore.QRect(10, 110, 81, 16))
    compliance_label.setObjectName("compliance_label")
    compliance_field = QtGui.QLineEdit(step_groupbox)
    compliance_field.setGeometry(QtCore.QRect(120, 110, 151, 25))
    compliance_field.setObjectName("compliance_field")
    value_init.setText("Valor inicio: ")
    value_interval.setText("Intervalo: ")
    step_number.setText("Numero de pasos: ")
    compliance_label.setText("Compliance: ")
    return step_groupbox

def get_sweep_groupbox():
    sweep_groupbox = QtGui.QGroupBox()
    sweep_groupbox.setGeometry(QtCore.QRect(30, 20, 271, 131))
    #sweep_groupbox.setGeometry(QtCore.QRect(0, 0, 271, 131))
    sweep_groupbox.setTitle("")
    sweep_groupbox.setObjectName("sweep_groupbox")
    val_stop_field = QtGui.QLineEdit(sweep_groupbox)
    val_stop_field.setGeometry(QtCore.QRect(100, 80, 161, 25))
    val_stop_field.setObjectName("val_stop_field")
    sweep_type_label = QtGui.QLabel(sweep_groupbox)
    sweep_type_label.setGeometry(QtCore.QRect(6, 10, 81, 20))
    sweep_type_label.setObjectName("sweep_type_label")
    comboBox = QtGui.QComboBox(sweep_groupbox)
    comboBox.setGeometry(QtCore.QRect(100, 10, 161, 25))
    comboBox.setObjectName("sweep_type_combobox")
    comboBox.addItem("Lineal")
    comboBox.addItem("Log10")
    comboBox.addItem("Log25")
    comboBox.addItem("Log50")
    value_stop = QtGui.QLabel(sweep_groupbox)
    value_stop.setGeometry(QtCore.QRect(10, 90, 71, 16))
    value_stop.setObjectName("value_stop")
    value_init = QtGui.QLabel(sweep_groupbox)
    value_init.setGeometry(QtCore.QRect(10, 50, 71, 16))
    value_init.setObjectName("value_init")
    value_init.setText("Valor inicio: ")
    value_stop.setText("Valor final: ")
    val_inicio_field = QtGui.QLineEdit(sweep_groupbox)
    val_inicio_field.setGeometry(QtCore.QRect(100, 50, 161, 25))
    val_inicio_field.setObjectName("val_inicio_field")
    return sweep_groupbox
